### ISSUE TITLE
work directory not tidied up and data saved twice

### ISSUE THREAD

**Issue by ghost** [esm-tools/esm_tools#96]
Hi,
I simulated to years of ECHAM standalone simulations with located at

`/mnt/lustre02/work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/test_run_new2`

My problem is that the directories are apparently not tiedied up correctly. The work directories (e.g. `run_18500101-18501231/work`) still contain all of the output data.
It seems that the output data start to be moved to the general `outdata` directory, however this stops after moving some few files and the rest of the data output is stored in the `unknown` folder. So, the data are finally stored twice: once in e.g. `run_18500101-18501231/work`  and once in the `unknown` folder.

My esm tools are located at 

`/work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/esm_tools`

Cheers Johannes

**Comment by mandresm** [comment]
Hi Johannes,

This is a known issue and it is in our TODO list (already mentioned in issue #55).

The reasons for not cleaning these folders are safety related (i.e. trying to restart a model that has crashed before or during moving files around could become a tedious task to debug). We have a few solutions in mind that we want to implement but we still need a bit of time. Maybe this would be a feature for `release 5.0`. You can read more about it here:

https://esm-tools.readthedocs.io/en/develop/esm_runscripts.html#experiment-directory-structure

That the data is copied to the `unknown` folder after a given time is certainly weird, so I'll have a look into this.

**Comment by mandresm** [comment]
Can you provide the path of the runscript you are using?

**Comment by ghost** [comment]
`/work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/test_run_new2/scripts/echam_johannes.yaml`

**Comment by mandresm** [comment]
Hi Johannes,

I think that ESM-Tools is doing the job as I would expect: please look at the ECHAM configuration file `/work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/esm_tools/configs/echam/echam.yaml` in the files section:

```
390 streams:
391         - echam
392         - accw
393         - co2
394         - g3bid
395         - g3bim
396         - g3bday
397         - g3b1hi
398         - glday
399         - aclcim
400         - sp6h
401         - glim
402         - spim
403 
404           #prev_date: 18500101
405 # BUG: PG Why do we need lists here?
406 
407 
408 
409 other_date: $(( ${next_date} - ${time_step}seconds ))
410 
411 ignore_files:
412         "[[streams-->STREAM]]": STREAM
413         "[[streams-->STREAM]]_restart": STREAM_restart
414         "[[streams-->STREAM]]_codes": STREAM_codes
415 
416 ignore_sources:
417         "[[streams-->STREAM]]": ${general.expid}_${next_date!syear!smonth}.${next_date!sday}_STREAM
418         "[[streams-->STREAM]]_restart": restart_${general.expid}_STREAM.nc
419         "[[streams-->STREAM]]_codes": ${general.expid}_${next_date!syear!smonth}.${next_date!sday}_STREAM.codes
420 
421 ignore_in_work:
422         "[[streams-->STREAM]]": ${general.expid}_${next_date!syear!smonth}.${next_date!sday}_STREAM
423         "[[streams-->STREAM]]_restart": restart_${general.expid}_STREAM.nc
424         "[[streams-->STREAM]]_codes": ${general.expid}_${next_date!syear!smonth}.${next_date!sday}_STREAM.codes
425 
426 
427 outdata_files:
428         "[[streams-->STREAM]]": STREAM
429         "[[streams-->STREAM]]_codes": STREAM_codes
430 
431 outdata_sources:
432         "[[streams-->STREAM]]": ${general.expid}_${start_date!syear!smonth}.${start_date!sday}_STREAM
433         "[[streams-->STREAM]]_codes": ${general.expid}_${start_date!syear!smonth}.${start_date!sday}_STREAM.codes
434 
435 outdata_in_work:
436         "[[streams-->STREAM]]": ${general.expid}_${start_date!syear!smonth}.${start_date!sday}_STREAM
437         "[[streams-->STREAM]]_codes": ${general.expid}_${start_date!syear!smonth}.${start_date!sday}_STREAM.codes
```

Note that `ignore_in_work` is including the STREAM files of the `next_date` (line 422). `next_date` is a ESM-Tools variable that gives the date of the following time step. This means that all outdata STREAM files will be ignored and therefore, not copied to the outdata folder. The only files that will be copied to the outdata folder are the ones included in the `outdata_in_work` whose time label is `start_date` (not `next_date`), where `start_date` is the start time of each run (in your case yearly runs). This means that you should have in outdata the output files whose names include `185001.01` for the first run and `185101.01` for the second run, which are present in your outdata folder.

By default, any file that has not being copied from the run folder to another folder in the general experiment, it is copied to the unknown folder. This means that the ignored files (those whose names contain 185002.01, 185003.01, ..., 185102.01, 185103.01, ...) will be copied to the unknown folder.

We understand that this situation is not ideal. In the future it will be up to the user if the run folders are deleted or not. Also ignored files could be deleted in the future. For now you can choose to manually delete your run folders, but I would recommend to leave at least the last 2 run folders intact, so that you can always come back to 1 or 2 runs before your current ongoing run.

Also note that the `final_date` of your runscript is `1851-02-01` which means the whole year run is not finished. To run it until the end of the year please use `1851-12-31`.

I hope this is useful, and please don't hesitate to post more questions on this issue.

**Comment by ghost** [comment]
Hi Miguel,

Thank you for the clarification of this issue and for the workaround proposal.

About the final date: Yes I was aware of that, but as you can see from the output files in the directory  `/mnt/lustre02/work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/test_run_new2/run_18510101-18511231/work`, it seems to somehow finish the entire year despite final date is set to `1851-02-01`. Nothing serious, but just to mention it ...

**Comment by mandresm** [comment]
Good to know, I'll have a look into that.

**Comment by dbarbi** [comment]
as Paul wrote above, this has been solved by a feature to be released in version 5.0, near future.

**Comment by chrisdane** [comment]
Model output is still not moved from `expname/run_YYYY0101-YYYY1231/work` to `expname/outdata/model` in
```
version = esm_tools, version 6.13.0
branch  = release
hash    = 845a535d
src     = /home/a/a270073/esm/esm_tools
```
Would be good to have it to save a lot of disk space. Maybe as a switch that the user can decide if copying or moving should be used?

Cheers,
Chris

**Comment by pgierz** [comment]
> Maybe as a switch that the user can decide if copying or moving should be used?

That exists. See the handbook: https://esm-tools.readthedocs.io/en/latest/esm_runscripts.html?highlight=movement#setting-the-file-movement-method-for-filetypes-in-the-runscript

**Comment by pgierz** [comment]
Which model output is left behind? And: Can you also post the path to your runscript? That seems like something in the YAML is (still) misconfigured for the ReCOM variant. AWI-ESM at least never has this problem anymore...

**Comment by nwieters** [comment]
Hi @chrisdane ,
did the comment by @pgierz solve your issue?
If not, can you please provide a link to an example runscript or experiment where you still have this issue?
Otherwise, can the issue be closed?

Thank you.
